# Generated by Django 5.1.6 on 2025-03-11 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RangeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.CharField(max_length=5)),
                ('action', models.CharField(choices=[('raise', 'Raise'), ('limp', 'Limp')], max_length=5)),
                ('stack', models.IntegerField(default=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.position')),
            ],
            options={
                'unique_together': {('position', 'hand', 'stack')},
            },
        ),
    ]
