# Generated by Django 5.1.6 on 2025-03-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackDepth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
            ],
        ),
    ]
