# Generated by Django 5.1.6 on 2025-03-12 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0004_rangeentry_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeentry',
            name='stack_depth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poker.stackdepth'),
        ),
    ]
