# Generated by Django 5.1.6 on 2025-03-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0007_remove_rangeentry_stack'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rangeentry',
            unique_together={('position', 'hand', 'stack_depth')},
        ),
    ]
