# Generated by Django 5.1.6 on 2025-03-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0008_alter_rangeentry_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='abbreviation',
            field=models.CharField(default=None, max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(default='UTG'),
            preserve_default=False,
        ),
    ]
