# Generated by Django 5.1.6 on 2025-03-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0009_position_abbreviation_position_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance_from_button',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
