# Generated by Django 5.1.6 on 2025-03-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0010_position_distance_from_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangeentry',
            name='action',
            field=models.CharField(choices=[('raise', 'Raise'), ('limp', 'Limp'), ('n_a', 'n/a')], max_length=5),
        ),
    ]
