# Generated by Django 5.1.6 on 2025-03-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='due_date',
            field=models.IntegerField(),
        ),
    ]
